### PR TITLE
Enable websocket upgrades for connect listeners

### PR DESCRIPTION
**Pull request by mattclement**
Enable websocket upgrades for connect listeners

### CODE REVIEW

**Comment by rayward** [comment]
Are we aiming to get this merged to upstream Consul?

**Comment by mattclement** [comment]
> Are we aiming to get this merged to upstream Consul?

Nah, I hadn’t planned on it.

**Review by rayward — APPROVED** [review]

**Comment by rayward** [comment]
Guess we'll need to get this merged into the 1.12.3 branch too?

**Comment by mattclement** [comment]
> Guess we'll need to get this merged into the 1.12.3 branch too?

Yup, but since we're blocked on that branch, I left it for later. It should be easy to port, since I did it on accident at first.

**Review by splittingred — APPROVED** [review]

**Pull request merged**
